### ISSUE TITLE
静的リンクでビルドができない

### ISSUE THREAD

**Issue by roloa** [roloa/Cataclysm-DDA_variant#1]
ビルドするときはCDDAのディレクトリ内にあるビルド用スクリプトを叩きます。
`
./compile_static.sh
`

ビルド用スクリプトの中身は以下です。
<pre><code>
make CCACHE=1 RELEASE=1 MSYS2=1 SDL=1 TILES=1 SOUND=1 LOCALIZE=1 LANGUAGES=all LINTJSON=0 ASTYLE=0 RUNTESTS=0 STATIC=1
tput bel
</code></pre>

makeがビルドが進めていくと、makeは最終的に以下のコマンドで実行ファイルを作ろうとします。
<pre><code>
ccache g++ -Wl,-stack,12000000,-subsystem,windows -o cataclysm-tiles.exe objwin/tiles/action.o objwin/tiles/active_item_cache.o objwin/tiles/activity_handlers.o objwin/tiles/activity_item_handling.o objwin/tiles/activity_type.o objwin/tiles/addiction.o objwin/tiles/advanced_inv.o objwin/tiles/advanced_inv_area.o objwin/tiles/advanced_inv_listitem.o objwin/tiles/advanced_inv_pane.o objwin/tiles/ammo.o objwin/tiles/anatomy.o objwin/tiles/animation.o objwin/tiles/armor_layers.o objwin/tiles/artifact.o objwin/tiles/auto_note.o objwin/tiles/auto_pickup.o objwin/tiles/avatar.o objwin/tiles/avatar_action.o objwin/tiles/ballistics.o objwin/tiles/basecamp.o objwin/tiles/behavior.o objwin/tiles/behavior_oracle.o objwin/tiles/behavior_strategy.o objwin/tiles/bionics.o objwin/tiles/bionics_ui.o objwin/tiles/bodypart.o objwin/tiles/bonuses.o objwin/tiles/calendar.o objwin/tiles/cata_tiles.o objwin/tiles/cata_utility.o objwin/tiles/cata_variant.o objwin/tiles/catacharset.o objwin/tiles/char_validity_check.o objwin/tiles/character.o objwin/tiles/character_martial_arts.o objwin/tiles/clothing_mod.o objwin/tiles/clzones.o objwin/tiles/color.o objwin/tiles/computer.o objwin/tiles/condition.o objwin/tiles/construction.o objwin/tiles/construction_category.o objwin/tiles/consumption.o objwin/tiles/coordinate_conversions.o objwin/tiles/craft_command.o objwin/tiles/crafting.o objwin/tiles/crafting_gui.o objwin/tiles/crash.o objwin/tiles/creature.o objwin/tiles/creature_tracker.o objwin/tiles/cursesport.o objwin/tiles/damage.o objwin/tiles/debug.o objwin/tiles/debug_menu.o objwin/tiles/defense.o objwin/tiles/dependency_tree.o objwin/tiles/descriptions.o objwin/tiles/dialogue_win.o objwin/tiles/dispersion.o objwin/tiles/drawing_primitives.o objwin/tiles/dump.o objwin/tiles/editmap.o objwin/tiles/effect.o objwin/tiles/emit.o objwin/tiles/event.o objwin/tiles/event_bus.o objwin/tiles/event_statistics.o objwin/tiles/explosion.o objwin/tiles/faction.o objwin/tiles/faction_camp.o objwin/tiles/fault.o objwin/tiles/field.o objwin/tiles/field_type.o objwin/tiles/filesystem.o objwin/tiles/flag.o objwin/tiles/fungal_effects.o objwin/tiles/game.o objwin/tiles/game_inventory.o objwin/tiles/game_ui.o objwin/tiles/gamemode.o objwin/tiles/gates.o objwin/tiles/grab.o objwin/tiles/handle_action.o objwin/tiles/handle_liquid.o objwin/tiles/harvest.o objwin/tiles/help.o objwin/tiles/iexamine.o objwin/tiles/ime.o objwin/tiles/init.o objwin/tiles/input.o objwin/tiles/inventory.o objwin/tiles/inventory_ui.o objwin/tiles/item.o objwin/tiles/item_action.o objwin/tiles/item_category.o objwin/tiles/item_factory.o objwin/tiles/item_group.o objwin/tiles/item_location.o objwin/tiles/item_search.o objwin/tiles/item_stack.o objwin/tiles/iteminfo_query.o objwin/tiles/itype.o objwin/tiles/iuse.o objwin/tiles/iuse_actor.o objwin/tiles/iuse_software.o objwin/tiles/iuse_software_kitten.o objwin/tiles/iuse_software_lightson.o objwin/tiles/iuse_software_minesweeper.o objwin/tiles/iuse_software_snake.o objwin/tiles/iuse_software_sokoban.o objwin/tiles/json.o objwin/tiles/kill_tracker.o objwin/tiles/lightmap.o objwin/tiles/line.o objwin/tiles/live_view.o objwin/tiles/loading_ui.o objwin/tiles/lru_cache.o objwin/tiles/magic.o objwin/tiles/magic_enchantment.o objwin/tiles/magic_spell_effect.o objwin/tiles/magic_teleporter_list.o objwin/tiles/magic_ter_fur_transform.o objwin/tiles/main.o objwin/tiles/main_menu.o objwin/tiles/map.o objwin/tiles/map_extras.o objwin/tiles/map_field.o objwin/tiles/map_item_stack.o objwin/tiles/map_memory.o objwin/tiles/map_selector.o objwin/tiles/mapbuffer.o objwin/tiles/mapdata.o objwin/tiles/mapgen.o objwin/tiles/mapgen_functions.o objwin/tiles/mapgendata.o objwin/tiles/mapgenformat.o objwin/tiles/mapsharing.o objwin/tiles/martialarts.o objwin/tiles/material.o objwin/tiles/mattack_actors.o objwin/tiles/melee.o objwin/tiles/memorial_logger.o objwin/tiles/messages.o objwin/tiles/mission.o objwin/tiles/mission_companion.o objwin/tiles/mission_end.o objwin/tiles/mission_place.o objwin/tiles/mission_start.o objwin/tiles/mission_ui.o objwin/tiles/mission_util.o objwin/tiles/missiondef.o objwin/tiles/mod_manager.o objwin/tiles/mod_manager_ui.o objwin/tiles/mod_tileset.o objwin/tiles/monattack.o objwin/tiles/mondeath.o objwin/tiles/mondefense.o objwin/tiles/monexamine.o objwin/tiles/monfaction.o objwin/tiles/mongroup.o objwin/tiles/monmove.o objwin/tiles/monster.o objwin/tiles/monstergenerator.o objwin/tiles/morale.o objwin/tiles/morale_types.o objwin/tiles/mtype.o objwin/tiles/mutation.o objwin/tiles/mutation_data.o objwin/tiles/mutation_type.o objwin/tiles/mutation_ui.o objwin/tiles/name.o objwin/tiles/ncurses_def.o objwin/tiles/newcharacter.o objwin/tiles/npc.o objwin/tiles/npc_class.o objwin/tiles/npcmove.o objwin/tiles/npctalk.o objwin/tiles/npctalk_funcs.o objwin/tiles/npctrade.o objwin/tiles/options.o objwin/tiles/output.o objwin/tiles/overlay_ordering.o objwin/tiles/overmap.o objwin/tiles/overmap_connection.o objwin/tiles/overmap_location.o objwin/tiles/overmap_noise.o objwin/tiles/overmap_ui.o objwin/tiles/overmapbuffer.o objwin/tiles/panels.o objwin/tiles/path_info.o objwin/tiles/pathfinding.o objwin/tiles/pickup.o objwin/tiles/pixel_minimap.o objwin/tiles/pixel_minimap_projectors.o objwin/tiles/player.o objwin/tiles/player_activity.o objwin/tiles/player_display.o objwin/tiles/player_hardcoded_effects.o objwin/tiles/point.o objwin/tiles/popup.o objwin/tiles/posix_time.o objwin/tiles/profession.o objwin/tiles/projectile.o objwin/tiles/ranged.o objwin/tiles/recipe.o objwin/tiles/recipe_dictionary.o objwin/tiles/recipe_groups.o objwin/tiles/regional_settings.o objwin/tiles/relic.o objwin/tiles/requirements.o objwin/tiles/resource.o objwin/tiles/rng.o objwin/tiles/rotatable_symbols.o objwin/tiles/safe_reference.o objwin/tiles/safemode_ui.o objwin/tiles/savegame.o objwin/tiles/savegame_json.o objwin/tiles/savegame_legacy.o objwin/tiles/scenario.o objwin/tiles/scent_map.o objwin/tiles/scores_ui.o objwin/tiles/sdl_utils.o objwin/tiles/sdl_wrappers.o objwin/tiles/sdlsound.o objwin/tiles/sdltiles.o objwin/tiles/simplexnoise.o objwin/tiles/skill.o objwin/tiles/skill_boost.o objwin/tiles/sounds.o objwin/tiles/speech.o objwin/tiles/start_location.o objwin/tiles/stats_tracker.o objwin/tiles/stomach.o objwin/tiles/string_formatter.o objwin/tiles/string_id_null_ids.o objwin/tiles/string_input_popup.o objwin/tiles/submap.o objwin/tiles/suffer.o objwin/tiles/teleport.o objwin/tiles/text_snippets.o objwin/tiles/tileray.o objwin/tiles/timed_event.o objwin/tiles/trait_group.o objwin/tiles/translations.o objwin/tiles/trap.o objwin/tiles/trapfunc.o objwin/tiles/turret.o objwin/tiles/tutorial.o objwin/tiles/ui.o objwin/tiles/veh_interact.o objwin/tiles/veh_type.o objwin/tiles/veh_utils.o objwin/tiles/vehicle.o objwin/tiles/vehicle_display.o objwin/tiles/vehicle_group.o objwin/tiles/vehicle_move.o objwin/tiles/vehicle_part.o objwin/tiles/vehicle_selector.o objwin/tiles/vehicle_use.o objwin/tiles/version.o objwin/tiles/visitable.o objwin/tiles/vitamin.o objwin/tiles/wcwidth.o objwin/tiles/weather.o objwin/tiles/weather_data.o objwin/tiles/weather_gen.o objwin/tiles/wincurse.o objwin/tiles/wish.o objwin/tiles/worldfactory.o -static -lintl -liconv -LC:/msys64/mingw64/lib -lSDL2_mixer -lmingw32 -lSDL2 -mwindows -lpthread -lmpg123 -lshlwapi -lvorbisfile -lvorbis -logg -lflac -L/mingw64/lib -lmingw32 -lSDL2 -mwindows -Wl,--no-undefined -Wl,--dynamicbase -Wl,--nxcompat -Wl,--high-entropy-va -lm -ldinput8 -ldxguid -ldxerr8 -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lshell32 -lsetupapi -lversion -luuid -static-libgcc -lSDL2_ttf -lSDL2_image -Wl,--start-group -lharfbuzz -lfreetype -Wl,--end-group -lgraphite2 -lpng -lz -ltiff -lbz2 -lglib-2.0 -llzma -lws2_32 -lintl -liconv -lwebp -ljpeg -luuid -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lversion
</code></pre>
↑見にくすぎるのでちょっと抜粋。
`
ccache g++ -Wl,-stack,12000000,-subsystem,windows -o cataclysm-tiles.exe objwin/tiles/action.o objwin/tiles/active_item_cache.o
...(.oファイルの羅列)...
 objwin/tiles/wish.o objwin/tiles/worldfactory.o -static -lintl -liconv -LC:/msys64/mingw64/lib -lSDL2_mixer -lmingw32 -lSDL2 -mwindows -lpthread -lmpg123 -lshlwapi -lvorbisfile -lvorbis -logg -lflac -L/mingw64/lib -lmingw32 -lSDL2 -mwindows -Wl,--no-undefined -Wl,--dynamicbase -Wl,--nxcompat -Wl,--high-entropy-va -lm -ldinput8 -ldxguid -ldxerr8 -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lshell32 -lsetupapi -lversion -luuid -static-libgcc -lSDL2_ttf -lSDL2_image -Wl,--start-group -lharfbuzz -lfreetype -Wl,--end-group -lgraphite2 -lpng -lz -ltiff -lbz2 -lglib-2.0 -llzma -lws2_32 -lintl -liconv -lwebp -ljpeg -luuid -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lversion
`

そうすると、以下のエラーが出ます。
<pre><code>
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_fluidsynth.o):(.text+0x11): undefined reference to `__imp_delete_fluid_player'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_fluidsynth.o):(.text+0x1f): undefined reference to `__imp_delete_fluid_settings'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_fluidsynth.o):(.text+0x2d): undefined reference to `__imp_delete_fluid_synth'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_fluidsynth.o):(.text+0x3b): undefined reference to `__imp_fluid_player_add'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_fluidsynth.o):(.text+0x49): undefined reference to `__imp_fluid_player_add_mem'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_fluidsynth.o):(.text+0x57): undefined reference to `__imp_fluid_player_get_status'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_fluidsynth.o):(.text+0x65): undefined reference to `__imp_fluid_player_play'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_fluidsynth.o):(.text+0x73): undefined reference to `__imp_fluid_player_set_loop'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_fluidsynth.o):(.text+0x81): undefined reference to `__imp_fluid_player_stop'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_fluidsynth.o):(.text+0x8f): undefined reference to `__imp_fluid_settings_setnum'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_fluidsynth.o):(.text+0x9d): undefined reference to `__imp_fluid_synth_get_settings'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_fluidsynth.o):(.text+0xab): undefined reference to `__imp_fluid_synth_set_gain'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_fluidsynth.o):(.text+0xb9): undefined reference to `__imp_fluid_synth_sfload'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_fluidsynth.o):(.text+0xc7): undefined reference to `__imp_fluid_synth_write_s16'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_fluidsynth.o):(.text+0xd5): undefined reference to `__imp_new_fluid_player'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_fluidsynth.o):(.text+0xe3): undefined reference to `__imp_new_fluid_settings'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_fluidsynth.o):(.text+0xf1): undefined reference to `__imp_new_fluid_synth'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_modplug.o):(.text+0xd): undefined reference to `__imp_ModPlug_Load'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_modplug.o):(.text+0x1b): undefined reference to `__imp_ModPlug_Unload'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_modplug.o):(.text+0x29): undefined reference to `__imp_ModPlug_Read'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_modplug.o):(.text+0x37): undefined reference to `__imp_ModPlug_Seek'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_modplug.o):(.text+0x45): undefined reference to `__imp_ModPlug_GetSettings'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_modplug.o):(.text+0x53): undefined reference to `__imp_ModPlug_SetSettings'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_modplug.o):(.text+0x61): undefined reference to `__imp_ModPlug_SetMasterVolume'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_opus.o):(.rdata$.refptr.op_pcm_seek[.refptr.op_pcm_seek]+0x0): undefined reference to `op_pcm_seek'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_opus.o):(.rdata$.refptr.op_read[.refptr.op_read]+0x0): undefined reference to `op_read'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_opus.o):(.rdata$.refptr.op_seekable[.refptr.op_seekable]+0x0): undefined reference to `op_seekable'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_opus.o):(.rdata$.refptr.op_head[.refptr.op_head]+0x0): undefined reference to `op_head'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_opus.o):(.rdata$.refptr.op_free[.refptr.op_free]+0x0): undefined reference to `op_free'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libSDL2_mixer.a(music_opus.o):(.rdata$.refptr.op_open_callbacks[.refptr.op_open_callbacks]+0x0): undefined reference to `op_open_callbacks'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libharfbuzz.a(libharfbuzz_la-hb-uniscribe.o):(.text+0x825): undefined reference to `__imp_UuidCreate'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x88): undefined reference to `ZSTD_freeDStream'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0xf8): undefined reference to `ZSTD_freeCStream'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x17e): undefined reference to `ZSTD_freeDStream'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x19a): undefined reference to `ZSTD_freeCStream'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x27a): undefined reference to `ZSTD_compressStream'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x285): undefined reference to `ZSTD_isError'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x2f4): undefined reference to `ZSTD_getErrorName'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x380): undefined reference to `ZSTD_endStream'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x38b): undefined reference to `ZSTD_isError'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x3e4): undefined reference to `ZSTD_getErrorName'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x45a): undefined reference to `ZSTD_freeCStream'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x46a): undefined reference to `ZSTD_createCStream'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x484): undefined reference to `ZSTD_initCStream'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x48f): undefined reference to `ZSTD_isError'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x524): undefined reference to `ZSTD_getErrorName'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x60b): undefined reference to `ZSTD_decompressStream'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x616): undefined reference to `ZSTD_isError'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x622): undefined reference to `ZSTD_getErrorName'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x72a): undefined reference to `ZSTD_freeDStream'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x73a): undefined reference to `ZSTD_createDStream'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x74e): undefined reference to `ZSTD_initDStream'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x759): undefined reference to `ZSTD_isError'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x7c4): undefined reference to `ZSTD_getErrorName'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x82e): undefined reference to `ZSTD_maxCLevel'
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/lib\libtiff.a(tif_zstd.o):(.text+0x837): undefined reference to `ZSTD_maxCLevel'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:772: cataclysm-tiles.exe] エラー 1
</code></pre>

今思いつく原因...
- 必要なライブラリがインストールされてない？
- makeファイルが作るコマンドが間違ってる？

**Comment by lispcoc** [comment]
MSYS2環境は確か動的リンクでしかビルドできない制約があったかと思います。
Windows環境であれば、Visual Studioでビルドすることで静的リンクが使えたかと。
https://github.com/roloa/Cataclysm-DDA/blob/master/doc/COMPILING/COMPILING-VS-VCPKG.md

**Comment by roloa** [comment]
アドバイスありがとうございます！
Visual Studioを試してみます。

**Comment by roloa** [comment]
仮想環境のCentOS（7だったかな？）でビルドしたら上手くいきました。
で、いろいろあって、今後はうちのラズパイちゃんにビルドしてもらうことにします。
ビルド環境とか書いた方がよさそうだと思うけど、イマイチ把握してない初心者。
