### ISSUE TITLE
gitに追跡されないMOD置き場が欲しい

### ISSUE THREAD

**Issue by lispcoc** [roloa/Cataclysm-DDA_variant#27]
`data/mods/` フォルダに動作確認用にファイルを置くと、gitが追跡してしまうのでコミットするときに毎回取り出すかステージング対象外にするかしないといけないので面倒。
`data/mods/_mod_test/` みたいなフォルダを作って、ここに入れたファイルは追跡対象外にするなどしたい。

**Comment by roloa** [comment]
自分はあまり上手いやり方を知らないのですが、
.gitignoreを好きに追記しちゃっても大丈夫だと思います。
1番下のほうに、自分が好き勝手書いちゃってるので、そのあたりに適当に書き加えてみてください。
.gitignore編集のプルリクも送ってくれたら問題なければマージします。

**Comment by lispcoc** [comment]
#28 でプルリク作成しました。

**Comment by roloa** [comment]
data/modsディレクトリの中にもう一つディレクトリ(_mod_test)を作って、その中にmodinfo.jsonを含んだMODディレクトリを入れても、うまく動くのかな？
そのMODディレクトリが複数あってもうまくいくのかな？
やったことないからわかんないけど、とりあえずマージします！

問題なければクローズしといてくださいね。

**Comment by lispcoc** [comment]
マージどうもです。
無事動作しました。クローズしておきます。
